// Vendors the icons this app uses out of lucide-static and into src/lib/icons/icons.ts.
//
// The generated file is committed. Icons are part of the application, downloaded from the same origin
// as everything else — there is no icon CDN and no icon font — and a committed module means a clone
// renders correctly before `npm install` has run, and a diff shows exactly which glyphs changed.
//
// To add an icon: put its Lucide name in ICONS below, run `npm run icons`, and commit the result.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

/** Lucide icon names, sorted. Anything not listed here is not shipped. */
const ICONS = [
  'archive', 'archive-restore', 'arrow-left', 'ban', 'calendar', 'check', 'chevron-down',
  'chevron-left', 'chevron-right', 'chevron-up', 'circle', 'circle-alert', 'circle-arrow-up', 'circle-check',
  'circle-dashed', 'circle-dot', 'circle-user', 'clock', 'command', 'copy', 'corner-down-right', 'download',
  'ellipsis', 'external-link', 'file-text', 'filter', 'flag', 'folder', 'folder-kanban',
  'grip-vertical', 'image', 'inbox', 'info', 'key-round', 'layout-grid', 'link', 'list', 'loader-circle',
  'log-out',
  'maximize-2', 'menu', 'message-square', 'milestone', 'minimize-2', 'minus', 'moon', 'paperclip', 'panel-left', 'pencil',
  'plus', 'refresh-cw', 'search', 'settings', 'shield', 'signal-high', 'signal-low', 'signal-medium',
  'square-check-big', 'sun', 'tag', 'trash-2', 'triangle-alert', 'upload', 'user', 'user-plus',
  'users', 'x'
];

const body = /<svg[^>]*>([\s\S]*)<\/svg>/;

const pkg = JSON.parse(
  await readFile(resolve(root, 'node_modules/lucide-static/package.json'), 'utf8')
);

const entries = [];

for (const name of ICONS) {
  const file = resolve(root, 'node_modules/lucide-static/icons', `${name}.svg`);
  const svg = await readFile(file, 'utf8');
  const match = body.exec(svg);

  if (!match) {
    throw new Error(`${name}.svg does not look like a Lucide icon`);
  }

  // One line per icon: the source files are pretty-printed, and the whitespace is only markup noise
  // once the glyph is inlined into a <svg> this app draws itself.
  const markup = match[1].replace(/\s*\n\s*/g, '').trim();
  entries.push(`  '${name}': '${markup.replace(/'/g, "\'")}'`);
}

const out = `// Generated by scripts/build-icons.mjs from lucide-static@${pkg.version}. Do not edit by hand.
//
// Lucide (https://lucide.dev) is ISC licensed; see LICENSE-THIRD-PARTY.md.
// Each value is the inner markup of the 24x24 icon, drawn by Icon.svelte with a stroke of
// currentColor, so an icon is coloured and sized by the text around it.

export const icons = {
${entries.join(',\n')}
} as const;

export type IconName = keyof typeof icons;
`;

await mkdir(resolve(root, 'src/lib/icons'), { recursive: true });
await writeFile(resolve(root, 'src/lib/icons/icons.ts'), out, 'utf8');

console.log(`Wrote ${ICONS.length} icons from lucide-static@${pkg.version}.`);
